# Generated by Django 2.0.4 on 2018-05-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20180507_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.CharField(default='20', max_length=3, verbose_name='教师年龄'),
        ),
    ]
