# Generated by Django 2.0.4 on 2018-05-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('qdkf', '前端开发'), ('hdkf', '后端开发'), ('uisj', 'UI设计')], default='hdkf', max_length=6, verbose_name='课程类型'),
        ),
    ]
