# Generated by Django 2.0.4 on 2018-05-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='标签'),
        ),
    ]
