# Generated by Django 2.0.4 on 2018-05-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180502_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '找回密码'), ('reset_email', '修改邮箱')], max_length=15, verbose_name='发送方式'),
        ),
    ]
